# Generated by Django 3.2.25 on 2025-11-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(error_messages={'unique': 'Ya existe un libro con este ISBN.'}, max_length=13, unique=True),
        ),
    ]
